config/routes.rb
Choron::Application.routes.draw do
  get "bounty/show"

  resources :auctions

  resources :bounties

  post 'bids' => 'bids#create'
  post 'quickbid' => 'bids#quickbid'
  post 'shared_bids' => 'bids#create'
  
  get 'bids' => 'home#chore_market'
  get 'shared_bids' => 'home#chore_market'

  match '/shared_chores/uncontribute/:id' => 'shared_chores#uncontribute'
  match '/shared_chores/contribute/:id' => 'shared_chores#contribute'

  resources :shared_chores, concerns: :chores
  resources :shared_bids, concerns: :bids

  resources :chores

  resources :users, :user_sessions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'admin' => 'user_sessions#make_admin', :as => :admin
  match 'user_sessions/confirm_admin' => 'user_sessions#confirm_admin'

  put   '/chores/complete/:id' => 'chores#complete'
  get   '/chores/coop/:id' => 'chores#coop'
  post   '/chores/coop/:id' => 'chores#complete_coop'

  match '/chores/undo/:id' => 'chores#undo'
  match '/chores/delete_all/:id' => 'chores#destroy_with_auction'
  match 'chores/destroy_repeating_chore/:id' => 'chores#destroy_repeating_chore'

  match '/auctions/new/for_chore/:chore_id' => 'auctions#new'
  match '/auctions/new_bid/:auction_id' => 'bids#new'

  match '/home' => 'home#my_chores'
  match '/home/chore_market' => 'home#chore_market'
  match '/home/chore_market/:view' => 'home#chore_market'
  match '/users/:user_id/give_chorons' => 'home#give_chorons_form'
  match 'home/give_chorons' => 'home#give_chorons'
  match 'home/new_chore_auction' => 'home#make_chore_auction_form'
  match 'home/make_chore_auction' => 'home#make_chore_auction'
  get   'home/preferences' => 'home#get_preferences_list'
  get   'home/preferences/:scheduler_id' => 'home#show_preference'
  put   'home/preferences/:scheduler_id' => 'home#edit_preference'
  post  'update_prefs' => 'home#update_preferences'
  get   'clear_prefs' => 'home#clear_preferences'
  
  root :to => 'user_sessions#new', :as => :login

end

app/models/bounty.rb
class Bounty < ActiveRecord::Base
  has_paper_trail
  attr_accessible :chore_id, :user_id
  belongs_to :chore, :counter_cache => true
  belongs_to :user
end

app/controllers/bounties_controller.rb
class BountiesController < ApplicationController
  before_filter :require_user
  def show
    @bounty = Bounty.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @auction }
    end
  end
    before_filter :require_user
  
 def require_owner
     @bounty = Bounty.find(params[:id])
     owner = @bounty.user
     unless current_user == owner
        #DEBUG
        puts '********************NOT BOUNTY OWNER'
        #store_location
        flash[:notice] = 'I\'m sorry I can\'t let you do that, Dave.'
        redirect_to(controller: 'home', action: 'chore_market')
        return false
     end
     puts '**********BOUNTY OWNER'
    end

  before_filter :require_owner, only: ['edit','destroy']
    
  # GET /bounties
  # GET /bounties.json
  def index
    @bounties = Bounty.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @bounties }
    end
  end

  # GET /bounties/new
  # GET /bounties/new.json
  def new
    @bounty = Bounty.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @bounty }
    end
  end

  # GET /bounties/1/edit
  def edit
    @bounty = Bounty.find(params[:id])
    @chore_id = @bounty.chore_id
  end

  # POST /bounties
  # POST /bounties.json
  def create
    @bounty = Bounty.new(params[:bounty])
    @chore = Chore.find(@bounty.chore_id)
    if @chore.nil?
      puts "OH GOD WHY JESUS USE VALIDATORS COME ON NOW SERRIOUSLY GUYS"
    end
    @chore.value=params[:value][:val].to_i
    @chore.save
    #TODO: Make the bounty get a user's information
    #and update the user parameter accordingly.
    @bounty.user = current_user
    respond_to do |format|
      if not @chore.nil? and @bounty.save!
        format.html { redirect_to :bounties, :notice => 'bounty was successfully created.' }
        format.json { render :json => @bounty, :status => :created, :location => @bounty }
      else
        format.html { render :action => "new", notice: 'errors creating bounty.' }
        format.json { render :json => @bounty.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bounties/1
  # PUT /bounties/1.json
  def update
    @bounty = Bounty.find(params[:id])
    @chore = Chore.find(@bounty.chore_id)
    if @chore.nil?
      puts "OH GOD WHY JESUS USE VALIDATORS COME ON NOW SERRIOUSLY GUYS"
    end
    @chore.value=params[:value][:val].to_i
    @chore.save
    respond_to do |format|
      if @bounty.save
        format.html { redirect_to @bounty, :notice => 'bounty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @bounty.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bounties/1
  # DELETE /bounties/1.json
  #TODO: Remove this. Bounties should not be destroyed without a chore.
  def destroy
    @bounty = Bounty.find(params[:id])
    @bounty.destroy
    respond_to do |format|
      format.html { redirect_to controller: 'home', action: 'bounty_market' }
      format.json { head :no_content }
    end
  end
  
end

app/helpers/bounty_helper.rb
module BountyHelper
end

app/views/bounties/_form.html.erb
<%= form_for(@bounty) do |f| %>
  <% if @bounty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bounty.errors.count, "error") %> prohibited this bounty from being saved:</h2>

      <ul>
      <% @bounty.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :chore_id %>
  <%= f.collection_select :chore_id, Chore.all, :id, :name, :include_blank => false %>
  <div class="field">
    Value:<br />
    <%= number_field :value, :val %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bounties/edit.html.erb
<h1>Editing bounty</h1>

<%= render 'form' %>

<%= link_to 'Show', @bounty %> |
<%= link_to 'Back', bounties_path %>

app/views/bounties/index.html.erb
<h1>Listing bounties</h1>
<p id="notice"><%= notice %></p>
<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th>Issuer</th>
    <th></th>
    <th></th>
  </tr>

<% @bounties.each do |bounty| %>
  <tr>
    <td><%= bounty.chore.name %></td>
    <td><%= bounty.chore.value %></td>
    <td><%= bounty.user.username %></td>
    <td><%= link_to 'View', bounty %></td>
    <% if current_user == bounty.user %>
    <td>You own this bounty.</td>
    <% end %>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bounty', new_bounty_path %>

app/views/bounties/new.html.erb
<h1>New bounty</h1>

<%= render 'form' %>

<%= link_to 'Back', bounties_path %>

app/views/bounties/show.html.erb
<h1>Bounty</h1>
<p>
Bounty issued by <%=@bounty.user.username%>
</p>
<p>
Chore: <%=link_to(@bounty.chore.name,@bounty.chore)%>
</p>
<p>
<%if @bounty.chore.due_date.future?%>
  Expires at: <%=@bounty.chore.due_date%>
<%else%>
  Expired at: <%=@bounty.chore.due_date%>
<%end%>

</p>
Fee: <%=@bounty.chore.value%>
</p>
<p>
<%if not @bounty.chore.done%>
  <%if @bounty.chore.due_date.future?%>
    <%= link_to 'I did it!', "/chores/complete/#{@bounty.chore.id}", method: :put %>
  <%else%>
    Sorry, this bounty is expired
  <%end%>
<% elsif @bounty.chore.user==current_user%>
  <%= link_to "I didn't do it", "/chores/undo/#{@bounty.chore.id}", method: :put %>
<% else %>
  <%= "#{@bounty.chore.user.username} completed this chore already." %>
<%end%>
</p>