config/routes.rb
Choron::Application.routes.draw do
  get "bounty/show"

  resources :auctions

  resources :bounties

  post 'bids' => 'bids#create'
  post 'quickbid' => 'bids#quickbid'
  post 'shared_bids' => 'bids#create'
  
  get 'bids' => 'home#chore_market'
  get 'shared_bids' => 'home#chore_market'

  match '/shared_chores/uncontribute/:id' => 'shared_chores#uncontribute'
  match '/shared_chores/contribute/:id' => 'shared_chores#contribute'

  resources :shared_chores, concerns: :chores
  resources :shared_bids, concerns: :bids

  resources :chores

  resources :users, :user_sessions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'admin' => 'user_sessions#make_admin', :as => :admin
  match 'user_sessions/confirm_admin' => 'user_sessions#confirm_admin'

  put   '/chores/complete/:id' => 'chores#complete'
  get   '/chores/coop/:id' => 'chores#coop'
  post   '/chores/coop/:id' => 'chores#complete_coop'

  match '/chores/undo/:id' => 'chores#undo'
  match '/chores/delete_all/:id' => 'chores#destroy_with_auction'
  match 'chores/destroy_repeating_chore/:id' => 'chores#destroy_repeating_chore'

  match '/auctions/new/for_chore/:chore_id' => 'auctions#new'
  match '/auctions/new_bid/:auction_id' => 'bids#new'

  match '/home' => 'home#my_chores'
  match '/home/chore_market' => 'home#chore_market'
  match '/home/chore_market/:view' => 'home#chore_market'
  match '/users/:user_id/give_chorons' => 'home#give_chorons_form'
  match 'home/give_chorons' => 'home#give_chorons'
  match 'home/new_chore_auction' => 'home#make_chore_auction_form'
  match 'home/make_chore_auction' => 'home#make_chore_auction'
  get   'home/preferences' => 'home#get_preferences_list'
  get   'home/preferences/:scheduler_id' => 'home#show_preference'
  put   'home/preferences/:scheduler_id' => 'home#edit_preference'
  post  'update_prefs' => 'home#update_preferences'
  get   'clear_prefs' => 'home#clear_preferences'
  
  root :to => 'user_sessions#new', :as => :login

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :require_user
  before_filter :require_admin, only: [:make_chore_auction_form]
  before_filter :clear_admin, only: [:make_chore_auction]
  
  def my_chores
    #grabs user data to display chores in the template
    @user = current_user

    respond_to do |format|
      format.html # my_chores.html.erb
      format.json { render :json => @user }
    end
  end
  
  def chore_market
    #retrieves all chores in the view specified
    #(open, all, or closed)
    @view = params[:view] ? params[:view] : 'open'
    #@chores = Chore.where(:auctions_count => 1)
    @shared_chores=SharedChore.all
    @shared_chores.keep_if { |sc| sc.active? }
    @chores = Chore.where("auctions_count=1 OR bounties_count=1")
    #sorts chores, puts open on top
    #sorts open by which expires soonest,
    #and closed by which expired most recently
    sorted_open=@chores.find_all{|chore| chore.open?}.sort{|a,b| a.end_date <=> b.end_date}
    sorted_closed=@chores.find_all{ |chore| not chore.open? }.sort{ |b,a| a.end_date <=> b.end_date}
    @chores = sorted_open+sorted_closed
    @open_shared = @chores.select { |c| c.is_a? SharedChore and not c.active? }
    @chores.keep_if { |c| not c.is_a? SharedChore }
  end
  
  def make_chore_auction_form
    #makes new chore object for form structure
    @chore = Chore.new
    #also makes a sharedchore to deal with forms_for
    @shared_chore = SharedChore.new
    #makes auction object and attaches it
    @auction = Auction.new
    @auction.chore = @chore
    respond_to do |format|
      format.html # make_chore_auction_form.html.erb
      format.json { render :json => @user }
    end
  end
  
  def make_chore_auction
    @auction = Auction.new(params[:chore][:auction])
    chore_params=params[:chore]
    chore_type = params[:chore_type]
    chore_params[:auction]=@auction
    @chore = (params[:shared] and params[:shared].to_b) ? SharedChore.new(chore_params) : Chore.new(chore_params)
    @auction.chore = @chore
    @chore.auction = @auction
    Auction.transaction do
      respond_to do |format|
        if @auction.save and @chore.save
          @auction.delay(:run_at => @auction.expiration_date).close
          format.html { redirect_to('/home/chore_market', :notice => 'Chore auction created.') }
          format.json { render :json }
        else
          format.html { redirect_to('/home/chore_market', :notice => 'Could not create chore auction.') }
          format.json { render :json => @user_session.errors, :status => :unprocessable_entity }
        end
      end
    end
    @scheduler = ChoreScheduler.new(:respawn_time => params[:respawn], default_bids: {} )
    @scheduler.chore = @chore
    @chore.chore_scheduler = @scheduler
    @scheduler.save
    @chore.save
    if params[:respawn].to_i != 0
      run_at = Time.now + @scheduler.respawn_time
      @scheduler.delay(run_at: run_at).schedule_next(run_at)
    end
  end
  
  def give_chorons_form
    #gets user id from url parameters
    @user = User.find(params[:user_id])
    #displays form asking for amount of chorons
    respond_to do |format|
      format.html # give_chorons_form.html.erb
      format.json { render :json => @user }
    end
  end
  
  def give_chorons
    #uses parameters to find out
    #how many chorons were given and to whom
    @chorons = params[:user][:chorons].to_i
    @recipient = User.find(params[:user][:user_id])
    @giver = current_user
    #processes request in database
    success = @giver.give_chorons(@recipient, @chorons)
    #if both objects saved, display success
    respond_to do |format|
      if success
        format.html { redirect_to(@recipient, :notice => 'Gift successful.') }
        format.json { render :json }
      else
        format.html { redirect_to(@recipient, :notice => 'Gift could not be processed.') }
        format.json { render :json => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end
  def get_preferences_list
    @prefs = current_user.bid_prefs
  end
  def show_preference
    @user= current_user
    respond_to do |format|
      format.html # make_chore_auction_form.html.erb
      format.json { render :json => @user }
    end

  end
  def edit_preference
    @user=current_user
    @user.bid_prefs[Integer(params[:scheduler_id])]=
        {value: Integer(params[:value]),manual: params[:manual]}
    unless params[:manual]
      @user.auto_preferences([ChoreScheduler.find(params[:scheduler_id])])
    end
    respond_to do |format|
      if @user.save
        format.html { redirect_to('/home/preferences', :notice => 'Preferences edited.') }
        format.json { render :json }
      else
        format.html { redirect_to('/home/preferences', :notice => 'Could not edit preference.') }
        format.json { render :json => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update_preferences
    @user=current_user
    params[:amounts].each_pair {
      | sid, pref |
      cut = params[:cuts] ? params[:cuts][sid] : nil
      cut = (cut == "") ? nil : cut
      if @user.bid_prefs[Integer(sid)][:value] != Integer(pref) or (cut and @user.bid_prefs[Integer(sid)][:cut] != Integer(cut))
        @user.bid_prefs[Integer(sid)].update({value: Integer(pref), manual: true})
        if cut
          @user.bid_prefs[Integer(sid)][:cut] = Integer(cut)
        end
      end
    }
    respond_to do |format|
      if @user.save
        format.html { redirect_to('/home/preferences', :notice => 'Preferences updated.') }
        format.json { render :json }
      else
        format.html { redirect_to('/home/preferences', :notice => 'Could not update preferences.') }
        format.json { render :json => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end

  def clear_preferences
    @user=current_user
    schedulers = @user.bid_prefs.keys
    schedulers.map! {
      |s|
      ChoreScheduler.find s
    }
    @user.bid_prefs.clear
    @user.auto_preferences schedulers
    respond_to do |format|
      if @user.save
        format.html { redirect_to('/home/preferences', :notice => 'Preferences cleared.') }
        format.json { render :json }
      else
        format.html { redirect_to('/home/preferences', :notice => 'Could not clear preferences.') }
        format.json { render :json => @user_session.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def give_chore_form
    #gets user id from url parameters
    #displays form asking for amount of chorons
  end
  
  def give_chore
    #uses parameters to find out
    #how many chorons were given and to whom
    #processes request in database
    #if both objects saved, display success
  end

  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_chore_tools.html.erb
<td><%= chore.due_date.strftime('%a %b %d,%l:%M %p') %></td>
<% if chore.auction %>
  <td>
    <div style="float:left">
      Auction:&nbsp;
    </div>
    <div style="float:left">
      <%= link_to 'Show', chore.auction %>&nbsp;
      <%= link_to 'Edit', edit_auction_path(chore.auction)  %>
    </div>
  </td>
<% else %>
  <td>
    <div style="float:left">
      Bounty:&nbsp;
    </div>
    <div style="float:left">
      <%= link_to 'Show', chore.bounty%>&nbsp;
      <%= link_to 'Edit', edit_bounty_path(chore.bounty) %>
    </div>
  </td>
<% end %>
<td>
  <div style="float:left">
    Chore:&nbsp;
  </div>
  <div style="float:left">
    <%= link_to 'Show', chore %>&nbsp;
    <%= link_to 'Edit', edit_chore_path(chore) %>
  </div>
</td>
<td><%= link_to 'Destroy chore/auction',
        "/chores/delete_all/"+chore.id.to_s, :data => { :confirm => 'Are you
  sure?' } %></td>
<td><%# link_to 'Take', "chores/take/"+chore.id.to_s %></td>

app/views/home/_market_row.html.erb
<% if chore.auction.expiration_date - Time.now < 604800 %>
<tr class="imminent">
<% else %>
<tr>
<% end %>
  <td><%= chore.name %></td>
  <% if chore.auction %>
    <% a_id = chore.auction.id.to_s %>
    <td><%= chore.auction.lowest %></td>
    <% if @view!="closed" %>
      <td>
        <% if chore.open? %>
          <% if flash[:qb_errors] and flash[:qb_errors][a_id] and
                 flash[:qb_errors][a_id].any? %>
            <% errors = flash[:qb_errors][a_id] %>
            <span class="qb_error">
              <% errors.full_messages.each do |msg| %>
                <%= msg %><br />
              <% end %>
            </span>
          <% end %>
          <input class="quickbid" id="qb<%=a_id%>"
                 name="amount[<%=a_id%>]" type="number"
                 tabindex="1" />
        <% end %>
      </td>
      <td>
        <% pref = chore.get_pref(current_user) %>
        <% if chore.open? and pref %>
          <input class="preference" type="button"
                 value="<%= pref[:value] %>"
                 onclick="document.getElementById('qb<%=a_id%>').value =
                          '<%= pref[:value] %>';
                          return false;" />
        <% end %>
      </td>
      <% end %>
    <td><%= chore.auction.expiration_date.strftime('%a %b %d,%l:%M %p') %></td>
    <%top_bid=chore.auction.bids.sort {|a,b| bid_sorter(a,b)}[0]%>
    <% if top_bid %>
      <td><%=top_bid.user.username%></td>
    <% else %>
      <td></td>
      <%end%>
    <% else %>
      <td><%= chore.value %></td>
      <td><%= chore.due_date.strftime('%a %b %d,%l:%M %p') %></td>
      <td></td>
    <% end %>
    <%= render 'chore_tools', chore: chore %>
</tr>

app/views/home/_shared_chore_row.html.erb
<tr>
  <td><%= link_to chore.name, chore_path(chore) %></td>
  <td><%= chore.value %></td>
  <td><% if chore.user != current_user
  %><span class="redacted">[redacted]</span><% else %>
  <%= chore.auction.lowest - chore.value %><% end %></td>
  <td><%= "%i/%i"%[chore.num_contributions(current_user),chore.num_contributions] %></td>
  <td>
    <% if chore.start_date %>
      <%= chore.start_date.strftime('%a %b %d,%l:%M %p') %>
    <% end %>
  </td>
  <td>
    <% if chore.due_date%>
      <%= chore.due_date.strftime('%a %b %d,%l:%M %p') %>
    <% end %>
  </td>
  <td>
    <% if chore.user%>
      <%= chore.user.username %>
    <% end %>
  </td>
  <td>
    <%= link_to 'I helped!', "/shared_chores/contribute/#{chore.id}" %>
  </td>
</tr>

app/views/home/_shared_market_row.html.erb
<% if chore.auction.expiration_date - Time.now < 604800 %>
<tr class="imminent">
<% else %>
<tr>
<% end %>
  <td><%= chore.name %></td>
  <%if chore.auction %>
        <% a_id = chore.auction.id.to_s %>
    <%top=chore.auction.bids.sort {|a,b| bid_sorter(a,b)}[0]%>
    <td><%= chore.auction.lowest %></td>
    <td>
      <%if top%>
        <%= top.amount %>
      <%end%>
    </td>
    <% if @view!="closed" %>
      <td>
        <% if chore.open? %>
          <% if flash[:qb_errors] and flash[:qb_errors][a_id] and
                 flash[:qb_errors][a_id].any? %>
            <% errors = flash[:qb_errors][a_id] %>
            <span class="qb_error">
              <% errors.full_messages.each do |msg| %>
                <%= msg %><br />
              <% end %>
            </span>
          <% end %>
          <input class="quickbid" id="qb<%=a_id%>" 
                 name="amount[<%=a_id%>]" type="number"
                 tabindex="1" />
        <% end %>
      </td>
      <td>
        <% if chore.open? %>
          <input class="quickbid" id="qbc<%=a_id%>" 
                 name="cut[<%=a_id%>]" type="number"
                 tabindex="1" />
        <% end %>
      </td>
      <td>
        <% pref = chore.get_pref(current_user) %>
        <% if chore.open? and pref %>
          <input class="preference" type="button"
                 value="<%= pref[:value].to_s + " / " + pref[:cut].to_s %>"
                 onclick="document.getElementById('qb<%=a_id%>').value =
                          '<%= pref[:value] %>';
                          document.getElementById('qbc<%=a_id%>').value =
                          '<%= pref[:cut] %>';
                        return false;" />
        <% end %>
      </td>
    <% end %>
    <td><%= chore.auction.expiration_date.strftime('%a %b %d,%l:%M %p') %></td>
    <%top_bid=chore.auction.bids.sort {|a,b| bid_sorter(a,b)}[0]%>
    <% if top_bid %>
      <td><%=top_bid.user.username%></td>
    <% else %>
      <td></td>
    <% end %>
  <% else %>
    <td><%= chore.value %></td>
    <td><%= TBI %></td>
    <td><%= chore.due_date.strftime('%a %b %d,%l:%M %p') %></td>
    <td></td>
  <% end %>
  <%= render 'chore_tools', chore: chore %>
</tr>

app/views/home/chore_market.html.erb
<h1>Chore market</h1>
<%= link_to 'All chores', '/chores' %>
<%= link_to 'All auctions', '/auctions' %>
<%= link_to 'All bounties', '/bounties' %>
<div id="views">
Now viewing <%= @view %> chore auctions and chore bounties. View:
  <%= link_to 'Open', :controller => "home", :action => "chore_market", :view => 'open' %> |
  <%= link_to 'Closed', :controller => "home", :action => "chore_market", :view => 'closed' %> |
  <%= link_to 'All', :controller => "home", :action => "chore_market", :view => 'all' %>
</div>
<% unless @shared_chores.empty? %>
  <h2>Available Shared Chores</h2>
  <table>
    <tr>
      <th>Chore name</th>
      <th>Pot</th>
      <th>Cut</th>
      <th>Times done</th>
      <th>Start Time</th>
      <th>End Time</th>
      <th>Overseer</th>
    </tr>
    
    <% @shared_chores.each do |chore| %>
      <%= render 'shared_chore_row',chore: chore %>
    <% end %>
  </table>
<% end %>

<form action="/quickbid" id="new_bids" method="post">
  <h2>Auctions</h2>
  <% if @view!='closed' %>
    <input name="commit" type="submit" value="Place Bids"
           tabindex="1" /><br />
  <% end %>
  <h3>Individual</h3>
  <input id="bid_user_id" name="user_id" type="hidden"
  value="<%= current_user.id %>" />
  <table>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <% if @view!='closed' %>
        <th>Bid</th>
        <th>Pref.</th>
      <% end %>
      <th>Closes</th>
      <th>Leader</th>
      <th>Chore Due</th>
      <th></th>
    </tr>

    <% @chores.each do |chore| %>
      <% if (@view=='open' and chore.open?) or
             (@view=='closed' and (not chore.open?)) or
             (@view=='all') %>
        <%= render 'market_row', chore: chore %>
      <% end %>
    <% end %>
  </table>
  <hr />
  <% unless @open_shared.empty? %>
    <h3>Shared</h3>
    <table>
      <tr>
        <th>Name</th>
        <th>Total</th>
        <th>Pot</th>
        <% if @view!='closed' %>
          <th>Pot Bid</th>
          <th>Cut Bid</th>
          <th>Prefs.</th>
        <% end %>
        <th>Closes</th>
        <th>Leader</th>
        <th>Chore Due</th>
        <th></th>
      </tr>

      <% @open_shared.each do |chore| %>
        <% if (@view=='open' and chore.open?) or
               (@view=='closed' and (not chore.open?)) or
               (@view=='all') %>
          <%= render 'shared_market_row',chore: chore %>
        <% end %>
      <% end %>
    </table>
    <hr />
  <% end %>
  <% if @view!='closed' %>
    <input name="commit" type="submit" value="Place Bids"
           tabindex="1" />
  <% end %>
</form>

Create a new: <ul>
<li><%= link_to 'Chore and auction', '/home/new_chore_auction' %></li>
<li><%= link_to 'Standalone chore (without auction or bounty)',
        new_chore_path %></li>
<li><%= link_to 'Auction (from existing standalone chore)',
        new_auction_path %></li>
<li><%= link_to 'Bounty (from existing standalone chore)', new_bounty_path %></li>
</ul>

app/views/home/delete_repeating_chore_form.html.erb
<h1>Delete repeating chore?</h1>
<%= form_for @chore, :url => { :action => "destroy_repeating_chore" } do |chore_form| %>

You just tried to delete the most recent instance of a repeating chore.
Would you like to stop the chore from repeating forever,
or just delete this instance of the chore?

<br/><%= radio_button_tag 'which_to_delete', 'chore', true %> Just delete this instance
<br/><%= radio_button_tag 'which_to_delete', 'scheduler' %> Stop the chore from repeating forever

<% end %>

app/views/home/get_preferences_list.html.erb
<h1>My preferences</h1>

<form method="post" id="bid_preferences" action="/update_prefs">
  <table>
    <tr>
      <th>Chore</th>
      <th>Amount</th>
      <th>Cut</th>
      <th>Manually set</th>
    </tr>

    <% @prefs.each do |scheduler_id,pref| %>
      <% scheduler=ChoreScheduler.find(Integer(scheduler_id))%>
      <% chore=scheduler.chore%>
      <% if chore %>
        <tr>
          <td><%= chore.name %></td>
          <td>
            <input name="amounts[<%= scheduler_id %>]"
                   value="<%= pref[:value] %>" />
          </td>
          <td>
            <% if chore.is_a? SharedChore %>
              <input name="cuts[<%= scheduler_id %>]"
                     value="<%= pref[:cut] %>" />
            <% end %>
          </td>
          <td><%= pref[:manual] %></td>
        </tr>
      <% end %>
    <% end %>
  </table>
  <br />
  <div>
    <input name="commit" type="submit" value="Update Preferences"
    style="float:left" />
    <a href="/clear_prefs" style="float:right">Clear preferences</a>
  </div>
</form>

app/views/home/give_chorons_form.html.erb
<%= form_for @user, :url => { :action => "give_chorons" } do |f| %>

  <div class="field">
    Chorons to give to <%= @user.username %>:<br />
    <%= f.text_field :chorons %>
    <%= f.hidden_field :user_id, value: @user.id %>
  </div>
  <div class="actions">
    <%= f.submit "Give Chorons" %>
  </div>
  
<% end %>

app/views/home/make_chore_auction_form.html.erb
<%= form_for @chore, :url => { :action => "make_chore_auction" } do |chore_form| %>

  <div class="field">
    <%= chore_form.label :name %><br />
    <%= chore_form.text_field :name %>
  </div>
  <div class="field">
    <%= chore_form.label :due_date %> for chore<br />
    <%= chore_form.datetime_select :due_date %>
  </div>
  
  <%= chore_form.fields_for @auction do |auction_fields| %>
    <div class="field">
      <%= auction_fields.label :expiration_date %> for auction<br />
      <%= auction_fields.datetime_select :expiration_date %>
    </div>
  <% end %>
  
  <div class="field">
      Repeats<br />
      <%= select_tag(:respawn, options_for_select([['every 5 min',300], ['Weekly',604800], ['Never',0], ['Monthly', 2419200] ])) %>
  </div>

  <div class="field">
    <label for="shared">Shared?</label><br />
    <input id="shared" name="shared" type="checkbox" />
  </div>

  <% #TODO: Add start date dialog box only if it is sharedchore %>

  <div class="field">
    Start date (if shared chore): <br />
    <%= chore_form.datetime_select :start_date %>
  </div>

  <div class="actions">
    <%= chore_form.submit "Make Chore Auction" %>
  </div>
  
<% end %>

app/views/home/my_chores.html.erb
<h1> My chores </h1>
<%= render "layouts/chore_table", chores_list: @user.prioratized_chores %>

<br />

<%= link_to 'New Chore', new_chore_path %>

app/views/home/show_preference.html.erb
<!--This file is not currently used, and likely will never be --!>
<%= form_tag(params[:chore_id] ,method: "put") do %>
  <%=label_tag(:value, "Value:")%>
  <%initial_value=current_user.bid_prefs[Integer(params[:chore_id])][:value]%>
  <%=text_field_tag(:value, initial_value)%>
  <br/>
  <%=submit_tag("Update Preference")%> 
<% end %>