config/routes.rb
Choron::Application.routes.draw do
  get "bounty/show"

  resources :auctions

  resources :bounties

  post 'bids' => 'bids#create'
  post 'quickbid' => 'bids#quickbid'
  post 'shared_bids' => 'bids#create'
  
  get 'bids' => 'home#chore_market'
  get 'shared_bids' => 'home#chore_market'

  match '/shared_chores/uncontribute/:id' => 'shared_chores#uncontribute'
  match '/shared_chores/contribute/:id' => 'shared_chores#contribute'

  resources :shared_chores, concerns: :chores
  resources :shared_bids, concerns: :bids

  resources :chores

  resources :users, :user_sessions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'admin' => 'user_sessions#make_admin', :as => :admin
  match 'user_sessions/confirm_admin' => 'user_sessions#confirm_admin'

  put   '/chores/complete/:id' => 'chores#complete'
  get   '/chores/coop/:id' => 'chores#coop'
  post   '/chores/coop/:id' => 'chores#complete_coop'

  match '/chores/undo/:id' => 'chores#undo'
  match '/chores/delete_all/:id' => 'chores#destroy_with_auction'
  match 'chores/destroy_repeating_chore/:id' => 'chores#destroy_repeating_chore'

  match '/auctions/new/for_chore/:chore_id' => 'auctions#new'
  match '/auctions/new_bid/:auction_id' => 'bids#new'

  match '/home' => 'home#my_chores'
  match '/home/chore_market' => 'home#chore_market'
  match '/home/chore_market/:view' => 'home#chore_market'
  match '/users/:user_id/give_chorons' => 'home#give_chorons_form'
  match 'home/give_chorons' => 'home#give_chorons'
  match 'home/new_chore_auction' => 'home#make_chore_auction_form'
  match 'home/make_chore_auction' => 'home#make_chore_auction'
  get   'home/preferences' => 'home#get_preferences_list'
  get   'home/preferences/:scheduler_id' => 'home#show_preference'
  put   'home/preferences/:scheduler_id' => 'home#edit_preference'
  post  'update_prefs' => 'home#update_preferences'
  get   'clear_prefs' => 'home#clear_preferences'
  
  root :to => 'user_sessions#new', :as => :login

end

app/models/chore.rb
class Chore < ActiveRecord::Base
  require File.join(Rails.root,"lib/taxation.rb")
  include Taxation
  attr_accessible :due_date, :name, :value, :done, :auction, :bounty, :auctions_count, :start_date
  belongs_to :user
  has_one :auction
  has_one :bounty
  belongs_to :chore_scheduler #might be nil if it is a one-time chore
  has_paper_trail
  accepts_nested_attributes_for :auction
  def open?
    if self.bounty
      return (not self.done and self.due_date.future?)
    elsif self.auction
      return self.auction.expiration_date.future?
    else
      return true
    end
  end
  def end_date
    if self.bounty
      return self.due_date
    elsif self.auction
      return self.auction.expiration_date
    else
      return nil
    end
  end
  def expected_value(testUser)
    if self.done
      return 0
    else
      return take_tax(self.user,self.value,testUser)
    end
  end
  def complete(current_user)
    if not self.done
      if self.auction
        if self.user==current_user
          take_tax(self.user,self.value)
          self.done=true
          Chore.transaction{self.save and self.user.save}
        end
      elsif self.bounty and self.due_date.future?
       self.user=current_user
       self.done=true
       current_user.chorons+=self.value
       self.bounty.user.chorons-=self.value
       Chore.transaction do
         current_user.save
         self.save
         self.bounty.user.save
       end
      end
    end
  end
  def complete_coop(recipients,current_user)
    if not self.done and self.auction and self.user==current_user
      Chore.transaction do
        multitax(recipients,self.value)
        self.done=true
        self.save
      end
    end
  end
  def undo(current_user)
    if self.user==current_user and self.done
      if self.auction
        take_tax(self.user,-self.value)
        self.done=false
        Chore.transaction do
          self.save
          self.user.save
        end
      elsif self.bounty
       self.user=nil
       self.done=false
       current_user.chorons-=self.value
       self.bounty.user.chorons+=self.value
       Chore.transaction do
         current_user.save
         self.save
         self.bounty.user.save
       end
      end
    end
  end

  def get_pref(user)
    if self.chore_scheduler
      return user.bid_prefs[self.chore_scheduler.id]
    else
      return nil
    end
  end
end

app/controllers/chores_controller.rb
class ChoresController < ApplicationController
  before_filter :require_user
  before_filter :require_admin, :only => [:edit, :new, :destroy, :destroy_with_auction]
  after_filter :clear_admin, only: [:update, :create, :destroy]
  
  # GET /chores
  # GET /chores.json
  def index
    @chores = Chore.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @chores }
    end
  end

  # GET /chores/1
  # GET /chores/1.json
  def show
    @chore = Chore.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @chore }
    end
  end
  
  #Takes the chore for current user
  def take_chore
    @chore = Chore.find(params[:id])
    current_user.chores << @chore
    
    respond_to do |format|
      if current_user.save
        format.html { redirect_to current_user, :notice => 'Chore was successfully taken.' }
      else
        format.html { render :action => "take" }
        format.json { render :json => @chore.errors, :status => :unprocessable_entity }
      end
    end
  end

  def complete
    Chore.find(params[:id]).complete(current_user)
    redirect_to(:back)
  end
  def complete_coop
    recipients=User.all.each_with_object({}) do |user,hash|
      hash[user]=params["Work#{user.id}"].to_f
    end
    Chore.find(params[:id]).complete_coop(recipients,current_user)
    redirect_to("/home")
  end
  def undo
    Chore.find(params[:id]).undo(current_user)
    redirect_to(:back)
  end
  def coop
    @chore =Chore.find(params[:id])
    unless (not @chore.done) and @chore.auction and @chore.user==current_user
      #If the above conditions aren't met, this should not work.
      redirect_to(:back)
    end
  end
  # GET /chores/new
  # GET /chores/new.json
  def new
    @chore = Chore.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @chore }
    end
  end

  # GET /chores/1/edit
  def edit
    @chore = Chore.find(params[:id])
  end

  # POST /chores
  # POST /chores.json
  def create
    @chore = (params[:shared] and params[:shared].to_b) ? SharedChore.new(params[:chore]) : Chore.new(params[:chore])

    respond_to do |format|
      if @chore.save
        format.html { redirect_to :chores, :notice => 'Chore was successfully created.' }
        format.json { render :json => @chore, :status => :created, :location => @chore }
      else
        format.html { render :action => "new" }
        format.json { render :json => @chore.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /chores/1
  # PUT /chores/1.json
  def update
    @chore = Chore.find(params[:id])
    respond_to do |format|
      if @chore.update_attributes(params[:chore])
        format.html { redirect_to @chore, :notice => 'Chore was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @chore.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /chores/1
  # DELETE /chores/1.json
  def destroy
    @chore = Chore.find(params[:id])
    #Check if the chore has a scheduler with a nonzero respawn time
    #If it does, take the user to the recurring chore deletion page
    if(@chore.chore_scheduler != nil and @chore.chore_scheduler.respawn_time != 0)
      puts "DEBUG: This is a recurring chore!"
      respond_to do |format|
        format.html
        format.json { render :json => @chore }
      end
    #If not, just destroy it, and take it to the chores url
    else
      @chore.destroy
      respond_to do |format|
        format.html { redirect_to controller: 'home', action: 'chore_market' }
        format.json { head :no_content }
      end
    end
  end
  
  def destroy_with_auction
    @chore = Chore.find(params[:id])
    @auction = @chore.auction
    #Check if the chore has a scheduler with a nonzero respawn time
    #If it does, take the user to the recurring chore deletion page
    if(@chore.chore_scheduler != nil and @chore.chore_scheduler.respawn_time != 0)
      puts "DEBUG: This is a recurring chore!"
      respond_to do |format|
        format.html { render 'chores/destroy' }
        format.json { render :json => @chore }
      end
    #If not, just destroy it, and take it to the chores url
    else
      @chore.destroy
      @auction.destroy if @auction != nil
      respond_to do |format|
        format.html { redirect_to controller: 'home', action: 'chore_market' }
        format.json { head :no_content }
      end
    end
  end
  
  def destroy_repeating_chore
    if params[:nevermind_button]
      respond_to do |format|
        format.html { redirect_to controller: 'home', action: 'chore_market' }
        format.json { head :no_content }
      end
    else 
      @chore = Chore.find(params[:id])
      if params[:all_button]
        puts "DEBUG: Delete it all!!11one1!"
        @chore.chore_scheduler.delete
        @chore.delete
        @auction.destroy if @auction != nil
        respond_to do |format|
         format.html { redirect_to controller: 'home', action: 'chore_market' }
          format.json { head :no_content }
        end
      else 
        if params[:instance_button]
          puts "DEBUG: Just delete this instance, please."
          @chore.chore_scheduler.schedule_next(Time.now)
          @chore.delete
          @auction.destroy if @auction != nil
          respond_to do |format|
            format.html { redirect_to controller: 'home', action: 'chore_market' }
            format.json { head :no_content }
          end
        end
      end
    end
  end

end

app/helpers/chores_helper.rb
module ChoresHelper
end

app/views/chores/_chore.html.erb
<p>
  <b>Name:</b>
  <%= chore.name %>
</p>

<p>
  <b>Due date:</b>
  <%= chore.due_date %>
</p>

app/views/chores/_form.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br />
    <%= f.datetime_select :start_date %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.datetime_select :due_date %>
  </div>
  <div class="field">
    <label for="shared">Shared?</label><br />
    <input id="shared" name="shared" type="checkbox" />
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/coop.html.erb
<%numPayers=User.where('is_frozen=?',false).length%>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"> </script>
<script>
  var choreValue=<%=@chore.value*numPayers.to_f/(numPayers-1)%>;
  var taxFrac=1.0/<%=numPayers%>;
  var totalWork;
  function update()
  {
    totalWork=
    <% User.all()[0..-2].each do |user| %>
      parseFloat($("#Work<%=user.id%>").val())+
    <% end %>
      parseFloat($("#Work<%=User.last.id%>").val());
    <% User.all().each do |user| %>
      $("#Share<%=user.id%>").text(((parseFloat($("#Work<%=user.id%>").val())/totalWork<%=user.is_frozen ? "":"-taxFrac"%>)*choreValue).toFixed(1));
    <% end %>
  }
  $(document).ready(function(){
    update()
    $("input").change(function(){update() });
  });
</script>
<h1>Divvy up the credit</h1>
Splitting the work on <%=@chore.name%> for <%=@chore.value%> chorons (post-tax):
<%= form_tag(@chore.id.to_s,method: "post") do %>
<table>
  <tr>
    <th>User</th>
    <th>Work done</th>
    <th>Profit</th>
  </tr>
  <% User.all().each do |user| %>
    <tr>
      <td><%= link_to user.username, "/users/#{user.id}" %></td>
      <td> <%=text_field_tag("Work#{user.id}", (user==current_user ? 1:0))%> </td>
      <td> <span id="Share<%=user.id%>">How is your internet this slow?</a> </td>
      <td> <%= user.is_frozen ? "(User is tax exempt)" :""%> </td>
    </tr>
  <% end %>
</table>
<%=submit_tag("Complete Chore")%> 
<%end%>

app/views/chores/destroy.html.erb
<h1>Delete repeating chore?</h1>
<% puts 'DEBUG: Evaluating the destroy form now!' %>
<%= form_for @chore, :url => { :action => "destroy_repeating_chore" } do |chore_form| %>
  <div class="info">
You just tried to delete the most recent instance of a repeating chore.
Would you like to stop the chore from repeating forever,
or just delete this instance of the chore?
</div>

<div class="actions">
  <%= submit_tag "Just delete this instance", :name => 'instance_button' %> 
  <%= submit_tag "Delete this and ALL future repetitions", :name => 'all_button' %> 
  <%= submit_tag "Nevermind. Don't delete it at all.", :name => 'nevermind_button' %>
</div>

<% end %>

app/views/chores/destroy_scheduler.html.erb
<%= form_for(@chore) do |f| %>
  <% if @chore.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chore.errors.count, "error") %> prohibited this chore from being saved:</h2>

      <ul>
      <% @chore.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :due_date %><br />
    <%= f.datetime_select :due_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/chores/edit.html.erb
<h1>Editing chore</h1>

<%= render 'form' %>

<%= link_to 'Show', @chore %> |
<%= link_to 'Back', chores_path %>

app/views/chores/index.html.erb
<h1>Listing chores</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Due date</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @chores.each do |chore| %>
  <tr>
    <td><%= chore.name %></td>
    <td><%= chore.due_date %></td>
    <td><%= chore.value %></td>
    <td><%= link_to 'Show', chore %></td>
    <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
    <td><%= link_to 'Destroy', chore, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    <td><%= link_to 'Take', "chores/take/"+chore.id.to_s %></td>
    <td><%= link_to 'Make Auction', "auctions/new/for_chore/"+chore.id.to_s %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Chore', new_chore_path %>

app/views/chores/new.html.erb
<h1>New chore</h1>

<%= render 'form' %>

<%= link_to 'Back', chores_path %>

app/views/chores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @chore.name %>
</p>

<p>
  <b>Due date:</b>
  <%= @chore.due_date %>
</p>

<% cs = ChoreScheduler.where("chore_id = " + @chore.id.to_s) %>
<% if cs.any? %>
  <p>
    <b>Repeats:</b>
    every <%= distance_of_time_in_words(Time.now, Time.now + cs.last.respawn_time) %>
  </p>
<% end %>

<% if @chore.is_a?(SharedChore) %>
  <p>
    <%= link_to 'I helped!', "/shared_chores/contribute/#{@chore.id}?user=#{current_user.username}" %>
  </p>
  <p>
    <b>Contributions:</b><br />
    <% contribs = [] %>
    <% @chore.contributions.each do |user, dates| %>
      <% dates.each_index do |i| %>
        <% contribs.push ({:user => user.username, :date => dates[i], :index => i}) %>
      <% end %>
    <% end %>
    <% contribs.sort_by! { |c| c[:date] } %>
    <% contribs.reverse! %>
    <%= render "layouts/contribution_table", contribs: contribs %>
  </p>
<% end %>

<%= link_to 'Edit', edit_chore_path(@chore) %> |
<%= link_to 'Back', chores_path %>