config/routes.rb
Choron::Application.routes.draw do
  get "bounty/show"

  resources :auctions

  resources :bounties

  post 'bids' => 'bids#create'
  post 'quickbid' => 'bids#quickbid'
  post 'shared_bids' => 'bids#create'
  
  get 'bids' => 'home#chore_market'
  get 'shared_bids' => 'home#chore_market'

  match '/shared_chores/uncontribute/:id' => 'shared_chores#uncontribute'
  match '/shared_chores/contribute/:id' => 'shared_chores#contribute'

  resources :shared_chores, concerns: :chores
  resources :shared_bids, concerns: :bids

  resources :chores

  resources :users, :user_sessions
  match 'login' => 'user_sessions#new', :as => :login
  match 'logout' => 'user_sessions#destroy', :as => :logout
  match 'admin' => 'user_sessions#make_admin', :as => :admin
  match 'user_sessions/confirm_admin' => 'user_sessions#confirm_admin'

  put   '/chores/complete/:id' => 'chores#complete'
  get   '/chores/coop/:id' => 'chores#coop'
  post   '/chores/coop/:id' => 'chores#complete_coop'

  match '/chores/undo/:id' => 'chores#undo'
  match '/chores/delete_all/:id' => 'chores#destroy_with_auction'
  match 'chores/destroy_repeating_chore/:id' => 'chores#destroy_repeating_chore'

  match '/auctions/new/for_chore/:chore_id' => 'auctions#new'
  match '/auctions/new_bid/:auction_id' => 'bids#new'

  match '/home' => 'home#my_chores'
  match '/home/chore_market' => 'home#chore_market'
  match '/home/chore_market/:view' => 'home#chore_market'
  match '/users/:user_id/give_chorons' => 'home#give_chorons_form'
  match 'home/give_chorons' => 'home#give_chorons'
  match 'home/new_chore_auction' => 'home#make_chore_auction_form'
  match 'home/make_chore_auction' => 'home#make_chore_auction'
  get   'home/preferences' => 'home#get_preferences_list'
  get   'home/preferences/:scheduler_id' => 'home#show_preference'
  put   'home/preferences/:scheduler_id' => 'home#edit_preference'
  post  'update_prefs' => 'home#update_preferences'
  get   'clear_prefs' => 'home#clear_preferences'
  
  root :to => 'user_sessions#new', :as => :login

end

app/views/layouts/_chore_row.html.erb
<tr>
  <% overdue = ((not chore.done) and chore.due_date.past? and
                (not chore.is_a?(SharedChore)))  %>
  <td class=<%= overdue ? 'overdue' : '' %>><%= chore.name %></td>
  <td class=<%= overdue ? 'overdue' : '' %>><%= chore.due_date.strftime('%a %b %d,%l:%M %p') %></td>
  <td class=<%= overdue ? 'overdue' : '' %>><%= chore.value %></td>
  <% if chore.is_a?(SharedChore) %>
    <td><%= "%i/%i"%[chore.num_contributions(current_user),chore.num_contributions] %></td>
  <% else %>
    <td class=<%= overdue ? 'overdue' : '' %>><%= chore.done %></td>
  <% end %>
  <% if current_user==chore.user %>
    <% if chore.is_a?(SharedChore) %>
      <td>
        <%= link_to 'I helped!',
            "/shared_chores/contribute/#{chore.id}?user=#{current_user.username}"
            %>
      </td>
      <td></td>
    <% else %>
      <% if chore.done %>
        <td>
          <%= link_to 'I didn\'t do it :(',
          "/chores/undo/#{chore.id}", method: :put %>
        </td>
      <% else %>
        <td>
          <%= link_to 'I did it!', "/chores/complete/#{chore.id}",
              method: :put %>
        </td>
      <% end %>
      <td><%= link_to 'We did it!', "/chores/coop/#{chore.id}" %></td>
    <% end %>
    <td><%= link_to 'Show', chore %></td>
    <td><%= link_to 'Edit', edit_chore_path(chore) %></td>
    <td><%= link_to 'Destroy', chore, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
    <td><%= link_to 'Give away', 'nosuchpage' %></td>
  <% end %>
</tr>

app/views/layouts/_chore_table.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Due date</th>
    <th>Value</th>
    <th>Done?</th>
  </tr>
  <% chores_list.each do |chore| %>
    <%= render "layouts/chore_row", chore: chore %>
  <% end %>
</table>

app/views/layouts/_contribution_row.html.erb
<tr>
  <td><%= contrib[:user] %></td>
  <td><%= contrib[:date] %></td>
  <td>
  <% if contrib[:user] == current_user.username %>
  <%= link_to 'I didn\'t do it!', "/shared_chores/uncontribute/#{@chore.id}?num=#{contrib[:index]}" %>
  <% end %>
  </td>
</tr>

app/views/layouts/_contribution_table.html.erb
<table>
  <tr>
    <th>Name</th>
    <th>Time</th>
  </tr>
  <% contribs.each do |contrib| %>
  <%= render "layouts/contribution_row", contrib: contrib %>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<html>
<head>
  <title>Choron. Brought to you by Castle Häuser™.</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= yield(:header) if @content_for_header %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if current_user %>
    <div id="user">
      Logged in as <%= current_user.username %>.<br />
      <%= link_to "Logout", :logout%>
    </div>
    <div class="chorons">Your chorons: <span class="chorons"><%= current_user.chorons %></span> <br/>
    <div class="expected-profit">
      <span class="expected-profit">Expected profit: </span>
      <table class="expected-profit">
      <tr class="numbers">
        <td class="numbers"> <%= current_user.expected_profit(:auction) %> </td>
        <td> <%= current_user.expected_profit(:shared_chore) >= 0 ? "+" : "-" %> </td>
        <td class="numbers"> <%= current_user.expected_profit(:shared_chore).abs %> </td>
        <td> <%= current_user.expected_profit(:chore) >= 0 ? "+" : "-" %> </td>
        <td class="numbers"> <%= current_user.expected_profit(:chore).abs %> </td>
        <td> = </td>
      </tr>
      <tr>
        <td class="labels" title="auctions">auctions</td>
        <td></td>
        <td class="labels" title="shared chores">shared chores</td>
        <td></td>
        <td class="labels" title="outstanding chores">outstanding chores</td>
        <td></td>
      </tr>
      </table>
      <span id="expected-profit-total"><%= sprintf("%+d",current_user.expected_profit) %></span>
      <a id="expected-profit-breakdown" onclick="toggleEP()" >show breakdown</a>
      </div>
    </div>
    <% if current_user.is_frozen %>
      <div id="frozen">
        <h1>YOUR USER ACCOUNT IS FROZEN.</h1>
        No taxes will be taken from this user until you are unfrozen.
      </div>
    <% end %>
  <%end%>
<div id="nav">
  <% if current_user %>
    <div class="navtab" id="<%= 'current' if(params[:controller] == 'home' and params[:action] == 'my_chores')%>"><%= link_to "My Chores", :controller => 'home', :action => 'my_chores' %></div>
    <div class="navtab" id="<%= 'current' if(params[:controller] == 'home' and params[:action] == 'chore_market')%>"><%= link_to "Chore Market", :controller => 'home', :action => 'chore_market' %></div>
    <div class="navtab" id="<%= 'current' if(params[:controller] == 'users' and params[:action] == 'index')%>"><%= link_to "All users", :users %></div>
    <div class="navtab" id="<%= 'current' if(params[:controller] == 'users' and params[:action] == 'edit')%>"><%= link_to "Edit Profile", edit_user_path(current_user.id)%></div>
    <div class="navtab" id="<%= 'current' if(params[:controller] == 'home' and params[:action] == 'get_preferences_list')%>"><%= link_to "Edit Bid Preferences", controller: 'home', action: 'get_preferences_list'%></div>
  <% else %>
    <div class="navtab" id="<%= 'current' if(params[:controller] == 'users' and params[:action] == 'new')%>"><%= link_to "Register", new_user_path %></div>
    <div class="navtab" id="<%= 'current' if(params[:controller] == 'user_sessions' and params[:action] == 'new')%>"><%= link_to "Login", :login %></div>
  <% end %>
</div>

<div id="main">
<%= yield %>
</div>
<div>
<a href="https://github.com/tigrennatenn/Choron/issues/new">Report a bug</a>
<%= flash.inspect %><br/>
<%= debug(params) if Rails.env.development? %>
<%= RUBY_VERSION %>
</div>
</body>
</html>